#constants:
#  file:
#    directory: D:\hc\backend\upload


Spring:
  application:
    name: On_Two_Day
  datasource:
    url: jdbc:mariadb://112.222.157.157:5012/first_project
    username: green2
    password: msa502


mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true