#constants:
#  file:
#    directory: D:\hc\backend\upload


Spring:
  application:
    name: On_Two_Day
  datasource:
    url: jdbc:mariadb://localhost/projectotd
    username: root
    password: green502


mybatis:
  mapper-locations: mappers/**/*.xml

  configuration:
    map-underscore-to-camel-case: true