#constants:
#  file:
#    directory: D:\hc\backend\upload

Spring:
  application:
    name: On_Two_Day
  datasource:
    url: jdbc:mariadb://112.222.157.157:5012/first_project
    username: green2
    password: msa502


mybatis:
  mapper-locations: mappers/**/*.xml

  configuration:
    map-underscore-to-camel-case: true

# weather api
constants:
  feign-client:
    weather-api:
      url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
      service-key: fte7et4WjQ2QQTSP51SJ6VZ%2FXA3aDUYv054aZFUsGdrVOKFJxQnmrKJGh%2Box%2FcnwsvpeJmLazXr4je1K01Uoow%3D%3D
      data-type: json
